version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: 'processingcenter'
    environment:
      POSTGRES_DB: processingcenter
      POSTGRES_USER: lesson
      POSTGRES_PASSWORD: lesson
    ports:
      - "5455:5432"
    volumes:
      # создание папки для подключения и хранения БД в проекте
#      - ./processingcenter-data:/var/lib/postgresql/data
#      - ./initdb:/docker-entrypoint-initdb.d
# смонтировать скрипт в контейнер в папку /docker-entrypoint-initdb.d/. Это делается через volumes.
      #
      #
        - ./sql/create-schemas.sql:/docker-entrypoint-initdb.d/01_create_schemas.sql
        - ./processingcenter-data:/var/lib/postgresql/data

#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq_pc
#    hostname: rabbitmq
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    ports:
#      - "5672:5672"    # AMQP протокол
#      - "15672:15672"  # Веб-интерфейс
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq
#    healthcheck:
#      test: ["CMD", "rabbitmqctl", "status"]
#      interval: 30s
#      timeout: 10s
#      retries: 5


  redis:
    image: 'redis:latest'
    restart: always
    container_name: redis_cache_pc
    ports:
      - "7479:6379"

 # processingcenter-api:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: processingcenter-api
  #  ports:
  #    - "8050:8050"
  #  depends_on:
  #    - postgres
  #    - redis

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin_pc
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8071:80"
    volumes:
      - pgadmin_data_pc:/var/lib/pgadmin

  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    container_name: processingcenter-swagger-ui
    ports:
      - "8076:8080"
    environment:
      SWAGGER_JSON: http://host.docker.internal:8080/v3/api-docs
      #SWAGGER_JSON: http://host.docker.internal:8050/v3/api-docs
      VALIDATOR_URL: "null"
      # чтобы Swagger не жаловался при отсутствии online-валидатора
#    depends_on:
#      - processingcenter
      #- processingcenter-api

  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jaeger
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"   # UI: http://localhost:16686
      - "14268:14268"   # gRPC (OTel exporter)
      - "14250:14250"   # HTTP (thrift)
      - "9411:9411"
      - "4317:4317"    # OTLP/gRPC
      - "4318:4318"    # OTLP/HTTP

volumes:
  pgadmin_data_pc:

networks:
  default:
    external:
      name: microservices-net

